var:
  url-repo: https://github.com/ludo2ne/ENSAI-2A-Projet-info   # to call this value : {{< meta var.url-repo >}}

project:
  type: website

website:
  title: "Projet info 2A"
  repo-url: "{{< meta var.url-repo >}}"
  repo-branch: main
  reader-mode: true
  navbar:
    background: "#447099"
    left:
      - icon: house
        href: index.qmd
        text: Home
      - text: Projet
        menu:
          - href: doc/projet/presentation-tuteurs.qmd
            text: "Présentation pour les tuteurs"
          - href: doc/projet/presentation-eleves.qmd
            text: "Présentation aux élèves"
          - href: doc/projet/notice-eleves.qmd
            text: "Notice élèves"
          - href: https://github.com/ludo2ne/ENSAI-2A-projet-info-template
            text: "Template"
          - href: doc/projet/sujets-2024-2025.qmd
            text: "Sujets 2024-2025"
      - text: Cours
        menu:
          - href: doc/cours/intro.qmd
            text: Introduction
          - href: doc/cours/outils-dev.qmd
            text: Outils de développement
          - href: https://ludo2ne.github.io/Git-tuto/doc/presentation.html
            text: Git
            target: "_blank"
          - href: doc/cours/analyse-fonctionnelle.qmd
            text: Analyse fonctionnelle
          - href: doc/cours/poo-avancee.qmd
            text: POO Avancée
          - href: doc/cours/tests-unitaires.qmd
            text: Tests unitaires
          - href: doc/cours/webservices.qmd
            text: Webservices
          - href: doc/cours/dao-securite.qmd
            text: DAO et Sécurité
      - text: TP
        menu:
          - href: doc/tp/tools.qmd
            text: Tools
          - href: doc/tp/tp1.qmd
            text: TP 1
          - href: doc/tp/tp2.qmd
            text: TP 2
          - href: doc/tp/tp3.qmd
            text: TP 3
          - href: doc/tp/tp4.qmd
            text: TP 4
    right:
      - text: Divers
        menu:
          - href: doc/divers/licences.qmd
            text: Licences
          - href: doc/divers/sigles.qmd
            text: Sigles
      - icon: github
        href: "{{< meta var.url-repo >}}"
        target: "_blank"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Code source]({{< meta var.url-repo >}}){.external target="_blank"}

format:
  html:
    theme:
      dark: solar
      light: cosmo
    css: styles.css
  revealjs:
    css: none
