var:
  url-repo: https://github.com/ludo2ne/ENSAI-2A-Projet-info   # to call this value : {{< meta var.url-repo >}}

project:
  type: website

author: 
  - Cyriel Mallart
  - Ludovic Deneuville
  - Rémi Pépin

website:
  title: "Projet info 2A"
  repo-url: "{{< meta var.url-repo >}}"
  repo-branch: main
  reader-mode: true
  navbar:
    background: "#23706B"
    left:
      - icon: house
        href: index.qmd
        text: Home
      - text: Project
        menu:
          - href: doc/projet/presentation-tuteurs.qmd
            text: "Présentation pour les tuteurs"
          - href: doc/projet/presentation-eleves.qmd
            text: "Présentation aux élèves"
          - href: doc/projet/notice-eleves.qmd
            text: "Notice élèves"
          - href: https://github.com/ludo2ne/ENSAI-2A-projet-info-template
            text: "Template"
          - href: doc/projet/sujets.qmd
            text: "Sujets"
      - text: Classes
        menu:
          - href: doc/cours/01-introduction.qmd
            text: Introduction
          - href: doc/cours/02-outils-dev.qmd
            text: Development Tools
          - href: doc/cours/03-git.qmd
            text: Git
          - href: doc/cours/04-analyse-fonctionnelle.qmd
            text: Functional Analysis
          - href: doc/cours/05-poo-avancee.qmd
            text: Advanced POO
          - href: doc/cours/06-tests-unitaires.qmd
            text: Unit Testing
          - href: doc/cours/07-webservices.qmd
            text: Webservices
          - href: doc/cours/08-dao-securite.qmd
            text: DAO and Security
      - text: Labs
        menu:
          - href: doc/tp/tp1.qmd
            text: Lab 1
          - href: doc/tp/tp2.qmd
            text: Lab 2
          - href: doc/tp/tp3.qmd
            text: Lab 3
          - href: doc/tp/tp4.qmd
            text: Lab 4
          - href: doc/tp/tp5.qmd
            text: Lab 5
          - href: doc/tp/tp6.qmd
            text: Lab 6 - Bonus
          - href: doc/tp/2025/tp1.qmd
            text: Old Labs
    right:
      - text: Various
        menu:
          - href: https://ludo2ne.github.io/ENSAI-tools/
            text: ENSAI-tools
            target: "_blank"
          - href: doc/divers/licences.qmd
            text: Licences
          - href: doc/divers/sigles.qmd
            text: Sigles
          - href: doc/divers/json-server.qmd
            text: Json-server
      - icon: github
        href: "{{< meta var.url-repo >}}"
        target: "_blank"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Code source]({{< meta var.url-repo >}}){.external target="_blank"}

format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    toc: true
    toc-location: left
    toc-depth: 2
  revealjs:
    theme: moon
    css: none
    slide-number: c/t
    slide-level: 3
    controls: true

execute:
  freeze: auto

from: markdown+emoji
lightbox: true