---
title: "Projet informatique 2e année"
description: "Ressources pour le projet informatique de 2e année de l'ENSAI"
author: "Ludovic Deneuville"
format: html
from: markdown+emoji
---

## Évolution potentielles pour 2025

- [ ] Dédoublement du cours (une partie de la promo suivra le cours et les TP en Anglais)
- [ ] Supports de cours et de TP en Anglais
- [ ] Utilisation du Datalab
  - La VM restera en backup
- [ ] Maj des TP2, 3, 4 (s'appuyer sur le template pour dev des fonctionnalités simples)

## Le projet info 2A

- [Présentation du projet aux tutrices et tuteurs](doc/projet/presentation-tuteurs.qmd)
- [Présentation du projet aux élèves](doc/projet/presentation-eleves.qmd)
- [Notice élèves](doc/projet/notice-eleves.qmd)

### Objectifs

Les élèves de deuxième année de l'ENSAI participent à la réalisation du projet informatique par groupes de 4 ou 5 élèves. 

Ce projet permet d’effectuer un approfondissement et une mise en pratique des connaissances acquises lors des enseignements informatiques de 1ère année.

Le travail demandé consiste à [construire une application]{.underline} permettant de répondre à la problématique d'un sujet proposé. Ce travail se décompose en 2 grandes phases : 

1. Étude préalable et Conception générale de l'application
  - décrire la solution envisagée
  - planifier les grandes phases de la réalisation
  - décrire les exigences fonctionnelles par la modélisation
2. Réalisation
  - mise en place de la base de données
  - développements, tests, documentation


## Le cours de Compléments d'informatique

::: {.callout-note}
Le but de ce cours est de vous aider à mener à bien le projet informatique en vous apportant les compétences et les outils nécessaires.
:::

[Cours 2023-2024](https://ludo2ne.github.io/ENSAI-2A-complement-info/){target="_blank"}

### Notions évoquées

- Git
- Rappels POO
- Tests unitaires
- Webservices
- Communiquer avec une base de données
- Utiliser les logs

### Les TP

4 TP de 3h permettent de mettre en applications les notions vues en cours. il y a également dans ces TP de nombreux éléments réutilisables en projet.

Le code des TP est disponible sur [ce dépôt](https://github.com/ludo2ne/ENSAI-2A-complement-info-tp/){target="_blank"}

## Bibliographie

- [Mise en production des projets de data science](https://ensae-reproductibilite.github.io/website/){target="_blank"}, Romain Avouac & Lino Galiana (ENSAE)
- [Refactoring.Guru](https://refactoring.guru/fr){target="_blank"}