---
title: "Introduction"
description: "[Slides](intro-slides.html)"
author: "Ludovic Deneuville"
format: 
  html:
    toc: true
    toc-location: left
    toc-depth: 2
  revealjs:
    theme: moon
    footer: "[Home](../../index.html) --- [Introduction](intro.html)"
    slide-number: c/t                    ## collapsed/total
    slide-level: 3
    controls: true
    output-file: intro-slides.html
from: markdown+emoji
lightbox: true
---

## Cours de Compléments d'info

- 6h CM
- 12h TP
- `ludovic.deneuville@ensai.fr`
- bureau 161
- sur la base des cours de [Rémi Pépin](https://github.com/HealerMikado){target="_blank"}

:::{.notes}
WIN + P : Etendre ou dupliquer

Présentation :

- 15 ans d'info (SQL, Java, Python)
- INSEE, informatique, Orléans GEOLOC, Lille enquêtes, Nautile
- ENSAI
- Rémi Pépin, assistant d'enseignement entre 2018 et 2023
  - Cours de Cloud Computing
:::

### Le cours

::: {.callout-tip title="But du cours"}
Vous apporter les connaissances nécessaires pour mener à bien un projet informatique.
:::

- Conduire un projet
- Dépasser les 50 lignes de code
- Vivre la vie de développeur
- Travailler en équipe

:::{.notes}
- Je reviens ensuite sur le projet
- Organiser votre code
:::

### Notions abordées

- Versionnage avec git
- Analyse fonctionnelle, Génie logiciel
- Programmation orientée objet avancée
- Communication avec une base de données en python
- Sécurité informatique
- Communication client-serveur

:::{.notes}
- Quelques rappels POO en TP
:::

### Les TP

- 4 x 3h
- Settings VScode, Formateur, Linter
- Suivez précisément les consignes, n'allez pas trop vite et ne sautez pas les étapes (:warning: Open Folder)

::: {.callout-warning}
**Vérifiez sur votre EDT si vous êtes en salle info !!!**
:::



:::{.notes}
- TP : truc à récup pour le projet
- Sujets très longs, travail à la maison
- Si un truc ne marche pas et que vous passez à la suite -> à un moment : BOOM
- Soyez solidaires

13/09 -> manque de salles info
:::

### Évaluation

- Lundi 7 Octobre 14h
- 2h
- sur papier
- 1 feuille A4 recto / verso **[manuscrite]{.underline}**

:::{.notes}
- But : voir si vous avez retenu le principal
- pas de piège
- sur papier car TP trop compliqué à organiser, chatGPT
- MANUSCRITE : pas de photocopie
:::

### Le projet info

[Présentation du projet](../projet/presentation-eleves.html){target="_blank"}

:::{.notes}
- N'oubliez pas vos voeux

Questions ?
:::