---
title: Lancement du projet info 2026-2027
description: "[Slides](reunion-lancement-slides.html)"
author: Ludovic Deneuville
format:
  html: default
  revealjs:
    theme: solarized
    footer: "[Home](../../index.html) --- [Lancement du projet info](reunion-lancement.qmd)"
    output-file: reunion-lancement-slides.html
number-sections: false
---


## Merci & Bienvenue


:::{.notes}
Rapide tour de table

- 1 min chacun (Localisation ? INSEE ? Ancien élève ? Domaine ?)
- Ensuite parlons rapidement Administratif et Logistique
- N'hésitez pas à m'interrompre si questions
:::

## MyENSAI

<https://genes.sharepoint.com/sites/MyEnsai>{target="_blank"}

- Pamplemousse : Scolarité, EDT, Appel
- [Moodle](https://foad-moodle.ensai.fr/){target="_blank"} : Contenu pédagogique
- Datalab : <https://datalab.sspcloud.fr/>{target="_blank"}
- VM : <https://view.ensai.fr/>{target="_blank"}

:::{.notes}
- MyENSAI : intranet, compte pour accéder à tout
  - Compte pnom
- Bascule mi-juillet
  - Nouveaux comptes créés ensuite par la scola
  - fournir : nom, prenom, tel, mail
:::

## Dossier Administratif {.smaller}

Quelques papiers pour être rémunéré

- Fiche de renseignement
- RIB
- Attestation sécu
- Décision d'engagement à signer
- Fiche de paie + attestation employeur (sauf INSEE)
- Autorisation de cumul (fonctionnaires)

À envoyer à `vacatairesensai@ensai.fr`

:::{.notes}
Vous recevrez un mail avec toutes les infos après la bascule Pamplemousse
:::

### Paie

2-3 mois après la fin de l'intervention

- décembre : TP
- mars : projet

Fiches de paie sur <https://ensap.gouv.fr/>{target="_blank"}


:::{.notes}
Créez un compte ENSAP avec votre numéro de sécu
:::

### Scolarité

Pour les questions d'emploi du temps :

- `scolarite@ensai.fr`
- `isabelle-laure.dang@ensai.fr`

N'oubliez pas de faire l'appel à chaque séance.

:::{.notes}
- Modop pour faire l'appel
  - Conseil : faire au début pour pas oublier
:::

### Frais

Si vous habitez **hors aire urbaine de Rennes**, vous êtes remboursés de :

- Billets de train 2e classe, metro, bus, ~~taxi~~
  - fournir des scans propres
- 20€ par repas
- Nuitée si pas possible d'arriver le matin même

`mission@ensai.fr`

:::{.notes}
Possible de demander l'achat direct de vos billet :

- Si vous ne voulez pas avancer les frais
- Si fait en avance > 15j

Note de frais à envoyer indiv ou par lots

Ticket Bus par CB.
:::

## Une journée à l'ENSAI

### Matin

- Salle indiquée dans Pamplemousse
- Et sur la télé à l'entrée du batiment

Vous pouvez passer si vous voulez bureau 161 (vers le fond aile administrative)

### Connectique

En salle, généralement de l'USB-C

Si besoin d'un autre type de cable, la DSI est au milieu du 1er étage.

Wifi: ENSAI (voir modop)

:::{.notes}
La DSI a déménagé.
:::


### Repas Midi

Entre 12h45 et 14h00, plusieurs possibilités :

- MSA ~ 15€
- [Ti-miam](https://timiam.fr/restaurant){target="_blank"} : Menu du jour à 15€
- Popotte personnelle

:::{.notes}
- ou Subway, Otacos, McDo
- 1h15 : Assez speed, ne pas trop trainer
- Restaurant du Forum : réserver
- Sympa de manger ensemble, après si vous mangez ailleurs n'hésitez pas à prévenir qu'on ne vous attende pas
- Végé ?
- Qui vient en voiture ?
:::

### Pause

10-15 min au milieu des séances (11h15 ou 15h25)

- Machines élèves au foyer (CB)
- Machine salle des permanents (pièces)
  - 1er étage, au milieu, face aux :toilet:

:::{.notes}
- Aussi fontaine à eau (chaude, froide, normale)
- Si vous manquez de sucre, j'ai de quoi faire
- Pauses : généralement je me balade dans les couloirs
- Pour me reconnaitre -> Linkedin, site GitHub
:::

## Les TP

### Techno et outils

- VSCode
- Python
- PostgreSQL
- Git

### Contenu

- TP1 : Outils, exemple d'application, rappels Git
- TP2 : Refactor, Design Pattern
- TP3 : DAO
- TP4 : Webservices
- TP5 : Frontend

:::{.notes}
Nouveaux sujets WIP

Quand vous avez TP + projet, l'ordre importe peu (sauf ATPA)
:::

### English

- 2 groups
- Full english
- Volunteers?

:::{.notes}
Sujets en anglais.

2A possible en full english (Erasmus).
:::

### Datalab

- <https://datalab.sspcloud.fr/>{target="_blank"}
- <https://onyxia.lab.groupe-genes.fr/>{target="_blank"}
  - Connexion avec votre compte ENSAI


::: {.callout-important}
Bien lire les consignes !
:::


:::{.notes}
- Lancer services
  - paramètres
  - open port
- suivre README
  - .env
  - run
  - api
  - inquirerPy
:::


### Accès VM

Backup :

- <http://view.ensai.fr/>{target="_blank"}
  - via navigateur
  - ou installer VMWare Horizon Client

:::{.notes}
VMWare Horizon Client : Désactiver la vérification de Certificat

CTRL + ALT + F12
:::

### Machine perso

::: {.callout-warning}
Élèves qui ne veulent pas travailler sur la VM :

- Installer IDE, Python, Git, BDD
- Manque de maîtrise
- Perte de temps
- TP DAO -> besoin d'une BDD
:::

:::{.notes}
- Ne soyez pas trop gentil
- Ne restez pas 3h avec eux pour installer
- ça ne leur rend pas service
- Surtout si vous voyez qu'ils ne maitrisent pas
:::



## Le projet

### Attendus

- Développer une application en Python
- Découvrir l'architecture logicielle
- Communiquer avec une base de données PostgreSQL
- Utiliser et/ou Créer des webservices
- Concevoir et Modéliser

:::{.notes}
- Profils d'élèves hétérogènes (MP, BUT, PC, BL, Eco, AST...)
- Des passionnés d'info, des refractaires.
- La marche est assez haute pour eux.
:::

### Sujets

- 20 août au plus tard dernier délai
- [Lien vers la liste](https://hackmd.io/qpcWPXGiSpi2kXOEJY41SQ){target="_blank"}

:::{.notes}
- Contraintes EDT
- Sinon : sujet mystère (les élèves n'aiment pas)
:::

### 1ère séance

- Présenter le sujet (diapo)
- Répondre aux questions
- Présenter votre mode de fonctionnement
- Pour les élèves
  - Recontrer son équipe
  - Lister les compétences
  - Répartir les rôles

:::{.notes}
Les étapes pour les élèves :

- lister les fonctionnalités
- modéliser (diag classe)
- créer la base de données
- coder

Les élèves sont sympas mais doivent être bien cadrés.
:::

### Suivi

- [Point hebdo](./notice-eleves.qmd#point-hebdo) jeudi soir
- Diagramme de Gantt
- Bien sonder le groupe si tout va bien
  - Prévenir au plus tôt si ça coince

:::{.notes}
Note de gestion de projet ?

- Inclure une backlog 
- En cas de soucis avec un élève ou une équipe :arrow_right: me prévenir
:::


### Usages de l'IA

Avec parcimonie, aide à la compréhension...

- Agent intégré dans VSCode
  - LLM SSP Cloud (ne va pas survivre à toute une promo)
  - Autre : Codestral

:::{.notes}
Bien insister que c'est pas magique :

- utilisé à bon escient ça aide
- mal utilisé, ça fait de la grosse mer**
:::

### Évaluations

- Dossier d'analyse
- Code
- Esprit d'équipe

:::{.notes}
- Dossier d'analyse
  - reçu samedi -> retour vendredi suivant
- Code -> grille notation
- Rapport -> grille, commun avec jury
:::


### Template

- [Modèle](https://github.com/ludo2ne/ENSAI-2A-projet-info-template){target="_blank"} qui peut servir de base :construction:
- Les élèves peuvent utiliser ou non
- Possibilité de fournir votre propre template


## Communiquer

- Mailing list
- [Serveur Discord](https://discord.gg/Sgh8XSYP){target="_blank"}
- Ludo : 06.45.45.40.82 ou 02.99.05.33.19
  - bureau 161 (1er étage, 3e gauche après passerelle)

:::{.notes}
N'hésitez pas à passer à mon bureau
:::
